events {}

http {
    # MIDDLEWARE: RATE LIMITING  
    # 'limit_auth' es estricto para el login (1 solicitud por segundo).
    # 'limit_api' es mas permisivo para uso general (10 solicitudes por segundo).
    limit_req_zone $binary_remote_addr zone=limit_auth:10m rate=1r/s;
    limit_req_zone $binary_remote_addr zone=limit_api:10m rate=10r/s;

    upstream backend {
        server ms1-1:3000;
        server ms1-2:3000;
    }

    upstream backend2 {
        server ms2-1:3000;
        server ms2-2:3000;
    }

    upstream backend3 {
        server ms3-1:3000;
        server ms3-2:3000;
    }

    server {
        listen 80;

        # MICROSERVICIO 1: AUTH 
        location /api1/ {
            # Aplicar Rate Limit estricto
            limit_req zone=limit_auth burst=5 nodelay;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }
            
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # MICROSERVICIO 2: VAULT
        location /api2/ {
            # Aplicar Rate Limit estándar
            limit_req zone=limit_api burst=20 nodelay;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_pass http://backend2/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MICROSERVICIO 3
        location /api3/ {
            limit_req zone=limit_api burst=20 nodelay;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_pass http://backend3/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}